config {
  type: "operations",     
  schema: "bqgcpmsdp_silver", // Opcional: o dataset onde a procedure será criada
  name: "screen_name_to_event_abertura_contas_viva_prime",
  tags: ["function"]    
}
CREATE OR REPLACE FUNCTION `${dataform.projectConfig.vars.data_product}.bqgcpmsdp_silver.screen_name_to_event_abertura_contas_viva_prime`(screen_name STRING) RETURNS STRUCT<event_journey STRING, event_sala STRING, event_postback STRING> AS (
CASE      
    WHEN screen_name = 'viva-afluente/afluente-viagens/sub-home-nao-filtrada' OR screen_name =  'viva-afluente/afluente-viagens/sub-home-filtrada'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'sub_home_viagens' AS event_sala, 'bq_af_sub_home_viagens_viva_prime_afluentes' AS event_postback)

    WHEN screen_name = 'viva-afluente/afluente-viagens/ordem-beneficios'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'ordem_beneficios_viagens' AS event_sala, 'bq_af_ordem_beneficios_viagens_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/afluente-viagens/filtrar-interesses'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'filtrar_interesses_viagens' AS event_sala, 'bq_af_filtrar_interesses_viagens_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/afluente-viagens/momentos'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'momentos_viagens' AS event_sala, 'bq_af_momentos_viagens_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/detalhe-do-parceiro/teste-afluente-pets' OR screen_name = 'viva-afluente/detalhe-do-parceiro/dizzy-vila=maria_exclusivo-menu'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'detalhes_do_parceiro_viagens' AS event_sala, 'bq_af_detalhes_do_parceiro_viagens_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/afluente-viagens/busca-origem-destino-com-localizacao'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'origem_e_destino_com_localizacao' AS event_sala, 'bq_af_origem_e_destino_com_localizacao_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/busca-de-parceiros-consulta'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'busca_de_parceiros' AS event_sala, 'bq_af_busca_de_parceiros_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/concierge'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'concierge' AS event_sala, 'bq_af_concierge_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/beneficios'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'beneficios' AS event_sala, 'bq_af_beneficios_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/beneficios/filtro-ordem-beneficios'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'modal_ordem_de_beneficios' AS event_sala, 'bq_af_modal_ordem_de_beneficios_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/beneficios/filtros'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'filtro_beneficios' AS event_sala, 'bq_af_filtro_beneficios_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/home'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'home_vitrine_de_beneficios' AS event_sala, 'bq_af_home_vitrine_de_beneficios_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/beneficios/vouchers'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'voucher' AS event_sala, 'bq_af_voucher_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/beneficios/vouchers/quer-mesmo-desistir-do-presente'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'desistir_do_presente' AS event_sala, 'bq_af_desistir_do_presente_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/beneficios/vouchers/agora-e-so-confirmar-os-dados-pra-resgate'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'confirmacao_resgate_voucher' AS event_sala, 'bq_af_confirmacao_resgate_voucher_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/vantagens'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'home_vantagens' AS event_sala, 'bq_af_home_vantagens_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/vantagens/cheque-especial'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'cheque_especial_vantagens' AS event_sala, 'bq_af_cheque_especial_vantagens_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/vantagens/convide-sua-familia'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'convide_sua_familia_vantagens' AS event_sala, 'bq_af_convide_sua_familia_vantagens_viva_prime_afluentes' AS event_postback)
       
    WHEN screen_name = 'viva-afluente/vantagens/cesta-de-servicos'
    THEN STRUCT('abertura_contas_viva_prime' AS event_journey, 'cesta_de_servicos_vantagens' AS event_sala, 'bq_af_cesta_de_servicos_vantagens_viva_prime_afluentes' AS event_postback)
       
  ELSE NULL
  END
);